Hikaya/Controllers/MessageController.cs
using Hikaya.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hikaya.Business.Interfaces;
using Hikaya.DAL;
using Hikaya.Helpers;
using Hikaya.Resources;

namespace Hikaya.Controllers
{
    public class MessageController : Controller
    {
        public readonly IStoryRepo storyRepo;
        public IFeedBackMessages feedBackMessageRepo;
        public MessageController(IStoryRepo storyRepo, IFeedBackMessages feedBackMessageRepo)
        {
            this.storyRepo = storyRepo;
            this.feedBackMessageRepo = feedBackMessageRepo;
        }
        // GET: Message
        public ActionResult Send(int id)
        {
            FeedbackMessage feedbackMessage = new FeedbackMessage();
            feedbackMessage.StoryId = id;
            feedbackMessage.Story = storyRepo.GetStoryById(id);

            return View(feedbackMessage);
        }

       
        [HttpPost]
        public ActionResult Send(FeedbackMessage model)
        {

            model.Date = DateTime.Now;
            model.UserId = UserHelper.GetCurrentUserId();
            feedBackMessageRepo.Add(model);
            TempData["SuccessMessage"] = StoryResourcesArabic.FeedBackSendMessage;
            return RedirectToAction("Index","Home");
        }

        public ActionResult Index()
        {
           
            return View();
        }
        public ActionResult Inbox()
        {
            var model = feedBackMessageRepo.GetAllFeedbackMessages(UserHelper.GetCurrentUserId());
            return View(model);
        }
    }
}

Hikaya/Views/Shared/_Layout.cshtml
@using Hikaya.Resources;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
   
    @*<a class="navbar-brand" href="/"><img class="logo" src="~/Images/Hikaya.png" /></a>*@
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(StoryResourcesArabic.ApplicationName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink(StoryResourcesArabic.MySavedStories, "SavedStories", "Story")</li>
                        <li>@Html.ActionLink(StoryResourcesArabic.Inbox, "Inbox", "Message")</li>
                    </ul>
                }
                

                @Html.Partial("_LoginPartial")
            </div>

        </div>
    </div>

    <div class="nanbar-collapse collapse">
        <div class="navbar-form">
            @using (Html.BeginForm("Search", "Home"))
            {
                <div class="row">
                    <div class="col-md-6" id="input-group-search">
                        <div class="input-group col-md-12">
                            <input type="text" class="form-group" name="keywords" placeholder="@StoryResourcesArabic.Search" />
                        </div>
                        <span class="input-group-btn">
                            <button class="btn btn-info btn-lg" type="submit">
                                <i class="glyphicon glyphicon-search">
                                </i>
                            </button>
                        </span>>
                    </div>
                </div>
            }
        </div>
    </div>

    <div class="container body-content">
        @if (TempData["successMessage"] != null)
        {
            <div class="alert alert-success">
                @TempData["successMessage"].ToString()

            </div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>